<template>
    <div>
      <div class="title">
        <img src="../../assets/images/octopus2.png" alt="">
        <b>Ops Privacy Policy</b>
      </div>
      <p><span>Ops is a social service provided by us. To illustrate how Ops collects, use and stores your personal information and what rights you have, we will explain to you through this guide. The main points are as follows:</span></p>
      <p><span>I. We will describe the types of personal information we collect about you and the purposes for which we collect it so that you can understand the types, reasons for use and methods of collection of specific personal information we collect about a particular function.</span></p>
      <p><span>II. Currently, Ops will not take the initiative to share or transfer your personal information to third parties, such as there are other sharing or transfer your personal information or you need us to share your personal information or transfer to a third party, we will confirm directly the consent or third party with your express consent to the above action, in addition, we will provide information to foreign conduct risk assessment.</span></p>
      <p><span>III. At present, for business development in Ops indirectly from a third party access to your personal information, we will express to you before getting your personal information source, type and scope of use, such as Ops do business need to personal information processing activities beyond when you provide personal information to a third party agreed scope of authorization, we will deal with you in the personal information, such as your express consent; In addition, we will strictly abide by relevant laws and regulations, and require third parties to guarantee the legality of the information they provide.</span></p>
      <p><span>IV. You may access, correct and delete your personal information through the channels listed in this Guideline, or you may withdraw your consent, cancel your account, lodge complaints and set up privacy functions.</span></p>
      <p><span>V. In order to collect your information or provide you with services, optimize our services and protect the security of your account under this Guidance, we will need to request permission from you; Sensitive permissions such as address book, precise geolocation, camera, microphone, photo album, etc. will not be enabled by default and will only be granted to us with your express consent.</span><br /><span>In particular, access to sensitive permissions is a necessary, not a sufficient, condition for us to collect specific information. Just because we have specific sensitive rights doesn&#8217;t mean we will necessarily collect information about you; Even if we have obtained sensitive permissions, we will only collect information about you in accordance with this guide when necessary.</span></p>
      <p><span>If you want more detailed information, please read the corresponding chapters according to the following index:</span><br /><span>1. The information we collect</span><br /><span>2. Information storage</span><br /><span>3. Information security</span><br /><span>4. How do we use information</span><br /><span>5. Offer</span><br /><span>6. Your Rights</span><br /><span>7. Protection of minors</span><br /><span>8. Other</span><br /><span>9. Contact us</span></p>
      <p> </p>
      <p><strong><span>1. The information we collect</span></strong></p>
      <p><span>During your use of Ops Service, Ops will collect the information you provide or generate as a result of using the Service in order to provide you with the service, optimize our service and protect your account security as follows:</span></p>
      <p><span>1.1 When you sign up for Ops service, we collect your nickname and avatar. This information is collected to help you complete Ops registration and protect your Ops account. You can choose to fill in information such as gender and region according to your needs. In addition, you may choose to provide us with your voiceprint eigenvalue information, which is sensitive information. Refusing to provide this information will only prevent you from using the voiceprint lock function, but will not affect your normal use of other functions of Ops.</span></p>
      <p><span>1.2 when you use the Ops service, to ensure your normal using our service, maintain the normal operation of our service, improve and optimize our service experience, and ensure the security of your account, we will collect your device model, operating system, IP address, Ops software version, access networks, data type and status, network quality, equipment accelerator (such as gravity sensing devices), operation logs and service log information (such as your search, check the operation record in Ops, service information such as fault information, referral url) such as logging information, this information is to provide information service must collect basis.</span></p>
      <p><span>1.3 When you use the address book feature, we will irreversibly encrypt your address book information and only collect the encrypted information. The above information is sensitive information. Refusing to provide this information will only make you unable to use the above functions, but will not affect your normal use of other functions of Ops.</span></p>
      <p><span>1.4 When you use Ops search, we will collect your search record, reading record, recommendation record and visit time, interaction record, in order to provide you with more accurate and personalized service and content.</span></p>
      <p><span>1.5 When you use Ops voice input, voice to text conversion, and Ops Translation functions, we will collect your voice content, the voice or text information to be converted, and the text information to be translated, as the collection is necessary to achieve the above functions. After we process it in real time, we return the results to you, we don&#8217;t save your data.</span></p>
      <p><span>1.6 When you use Ops to communicate with other software or hardware, the provider of other software or hardware may, with your consent, obtain information that you actively disclose or transmit in Ops. You should fully understand the product functions and information protection policies of other software or hardware before choosing.</span></p>
      <p><span>1.7 When you use the Ops Video Dynamic feature, the video information you upload will be stored on our server, as storage is required to implement this feature. We store it in encrypted form, and you can delete any video you upload at any time. We will not provide such information to the public or use it for any purpose other than this function unless you choose to do so or comply with the requirements of relevant laws and regulations.</span></p>
      <p><span>1.8 When you use Ops favorites to store all kinds of information, the information will be uploaded and stored on our server, so that you can use the information when you log in Ops on other devices, which is necessary to implement the favorites function. We will store your information in encrypted form, and you can delete your information at any time. We will not provide such information to the public or use it for any purpose other than this function unless you choose to do so or comply with the requirements of relevant laws and regulations.</span></p>
      <p><span>1.9 You may enter gender, region, signature, address, invoice title, etc. in your personal information field, which will be uploaded and stored on our servers for you to use when you log in Ops on other devices. You can also modify, delete such information at any time.</span></p>
      <p><span>1.10 Third party services in Ops service are provided by external third party principals, and Ops cannot access the information generated when you use such third party services. However, if you expressly consent to this third party obtaining your geolocation information, that third party will obtain your terminal geolocation information through the Ops interface. This information is sensitive information. Refusal to provide this information will only prevent you from using the above third party services, but will not affect your normal use of Ops functions.</span></p>
      <p><span>In addition, in accordance with applicable laws, regulations and national standards, we may collect and use your relevant personal information without requiring your authorized consent in the following circumstances:</span></p>
      <p><span>A) related to the performance of the obligations stipulated by laws and regulations by the personal information controller;</span><br /><span>B) those directly related to national security and national defense security;</span><br /><span>C) those directly related to public safety, public health and major public interests;</span><br /><span>D) those directly related to criminal investigation, prosecution, trial and execution of judgment;</span><br /><span>E) For the purpose of safeguarding the major legitimate rights and interests such as the life and property of the subject of personal information or other individuals, but it is difficult to obtain authorization and consent of the person;</span><br /><span>F) The personal information involved is disclosed to the public by the subject of personal information;</span><br /><span>G) necessary to sign and perform the contract according to the requirements of the subject of personal information;</span><br /><span>H) Collecting personal information from legally disclosed information, such as legitimate news reports, government information disclosure and other channels;</span><br /><span>I) Necessary to maintain the safe and stable operation of the product or service provided, such as the discovery and disposal of faults of the product or service;</span><br /><span>J) The person controlling personal information is a news agency, and it is necessary for it to carry out legitimate news reports;</span><br /><span>K) The personal information controller is an academic research institution. When it is necessary to carry out statistics or academic research in the public interest and it provides the results of academic research or description to the outside world, the personal information contained in the results is de-labeled.</span><br /><span>Please understand that the prices we offer you the functions and services are constantly updated and development, if a certain function or service is not in the foregoing statement and collected your information, we will have a page prompts, interactive process, such as web site announcement to tell you the content of the information collection, the scope and purpose, with your approval.</span></p>
      <p><span>Please note that Ops currently does not actively retrieve your personal information from a third party outside Ops. As for business development in the future from a third party of indirect access to your personal information, we will express to you before getting your personal information source, type and scope of use, such as Ops operations require personal information processing activities beyond when you provide personal information to a third party agreed scope of authorization, we will deal with you in the personal information, such as your express consent; In addition, we will strictly abide by relevant laws and regulations, and require third parties to guarantee the legality of the information they provide.</span></p>
      <p><strong><span>2. Information storage</span></strong></p>
      <p><span>2.1 Location of information storage</span><br /><span>We will store the personal information in HK that collected within China in accordance with laws and regulations. If your personal information is transferred from China to another country, we will strictly comply with the law.</span></p>
      <p><span>2.2 Term of information storage</span><br /><span>In general, we retain your personal information only for the period of time necessary to achieve our purposes, such as:</span><br /><span>Mobile phone number: If you need to use Ops service, we need to always save your mobile phone number, to ensure that you can use the service normally, when you cancel Ops account, we will delete the corresponding information;</span><br /><span>Happen to stop operating when our products or services, we will inform you in the form of push notifications, announcements, etc, and within a reasonable period of time to delete your personal information or deal with an anonymous (so-called &#8216;anonymous&#8217;, refers to the technical processing of personal information, makes the personal information subject cannot be identified, and after processing the information cannot be recovery process. Personal information obtained after anonymous processing does not belong to personal information. .</span></p>
      <p><strong><span>3. Information security</span></strong></p>
      <p><span>We strive to ensure the security of our users&#8217; information to prevent information loss, improper use, unauthorized access or disclosure.</span><br /><span>We will use a variety of security measures to ensure the security of information within a reasonable level of security. For example, we use encryption (e.g., SSL), anonymous processing, etc., to protect your personal information.</span><br /><span>We are constantly enhancing the security capabilities of the software installed on your device through improved technology to prevent the disclosure of your personal information. For example, we will encrypt some information locally on your device for secure transmission. In order to prevent viruses, Trojans or other malicious programs or websites, we may learn about the application information installed on your device, the running process information or the data stored in the device&#8217;s memory; In order to prevent fraud, number theft, impersonation and other illegal activities and conduct security checks, data such as unique device identifier, login IP address, operation log and geographic location information may be analyzed to facilitate the adoption of security measures or security reminders to users.</span><br /><span>We establish special management system, process and organization to ensure the security of information. For example, we strictly limit the number of people who can access information, require them to observe confidentiality obligations, and conduct audits.</span><br /><span>In case of security incidents such as personal information leakage, we will activate emergency plans to prevent the expansion of security incidents, and inform you in the form of push notifications, announcements, etc.</span><br /><span>We will do our best to protect your personal information. We also ask you to understand that no security measure can be perfect.</span></p>
      <p><strong><span>4. How do we use information</span></strong></p>
      <p><span>We may use the information collected through certain functions for our other services. We could, for example, when you use a function or service of the information we collect, in another function or service to provide specific content to you or your friends, including but not limited to display ads (you can know more in about AD pages), have you read the content of information security of class, based on the characteristics of the labels suggest indirectly portraits and provides more precise and personalized services and content, etc.</span><br /><span>To secure our services and help us better understand how our application is performing, we may record relevant information, such as how often you use the application, crash data, overall usage, performance data, and where the application came from. We will not combine the information we store in our analytics software with any personally identifiable information you provide in your application.</span><br /><span>If we use your personal Information in a way that is not directly or reasonably relevant to the purpose for which it was collected, we will notify you again and obtain your express consent before using your personal Information.</span></p>
      <p><strong><span>5. Offer</span></strong></p>
      <p><span>At this time, we do not actively share or transfer your personal information to third parties outside Ops. In the event of any other sharing or transfer of your personal information to third parties outside Ops where you require us to share or transfer your personal information to third parties outside Ops, we will directly or confirm that third parties have obtained your express consent to do so.</span><br /><span>We will not publicly disclose the personal information we collect. If necessary, we will inform you of the purpose of this public disclosure, the type of information disclosed and the sensitive information that may be involved, and we will obtain your express consent.</span><br /><span>When you log in to an application run by a third-party entity via Ops personal account, we will provide your personal information to such third-party entity. The specific scope of external provision is subject to your confirmation in the interactive page. In addition, we will not provide your personal information to such third parties without your express consent.</span><br /><span>As our business continues to grow, we may enter into mergers, acquisitions, asset transfers and other transactions, and we will inform you of the circumstances, the continued protection of your personal information in accordance with laws and regulations and standards not lower than those required by this Guidance or the requirement that new controllers continue to protect your personal information.</span><br /><span>In addition, in accordance with relevant laws, regulations and national standards, we may share, transfer or publicly disclose personal information in the following situations without prior authorization and consent of the subject of personal information:</span></p>
      <p><span>A) related to the performance of our obligations under laws and regulations;</span><br /><span>B) those directly related to national security and national defense security;</span><br /><span>C) those directly related to public safety, public health and major public interests;</span><br /><span>D) those directly related to criminal investigation, prosecution, trial and execution of judgment;</span><br /><span>E) For the purpose of safeguarding the major legitimate rights and interests such as the life and property of the subject of personal information or other individuals, but it is difficult to obtain authorization and consent of the person;</span><br /><span>F) Personal information disclosed by the subject to the public;</span><br /><span>G) Collecting personal information from legally disclosed information, such as legitimate news reports, government information disclosure and other channels.</span></p>
      <p><strong><span>6. Your Rights</span></strong></p>
      <p><span>To make it easier for you to access, correct and delete your personal information while using Ops, and to protect your right to withdraw your consent and cancel your account, we provide you with the appropriate operation Settings in the product design. You can refer to the following guidelines to do so. In addition, we have set up a complaint reporting channel, your opinions will be dealt with in a timely manner.</span></p>
      <p><strong><span>7. Protection of minors</span></strong></p>
      <p><span>We attach great importance to the protection of minors&#8217; personal information. According to relevant laws and regulations, if you are under the age of 18, you should obtain the prior written consent of your parent or legal guardian before using Ops. If you are the guardian of a minor, if you have any questions regarding the personal information of a minor under your guardianship, please contact us through the contact information in section 10.</span><br /><span>In particular, it is not recommended if you are a child under the age of 18.</span></p>
      <p><strong><span>8. Other</span></strong></p>
      <p><span>Ops Privacy Policy is a general privacy policy that applies uniformly to Ops, and the user rights and information security safeguards specified therein apply to Ops users. If Ops privacy Policy is inconsistent or inconsistent with this Guidance, please follow this guidance.</span></p>
      <p><strong><span>9. Contact us</span></strong></p>
      <p><span>If you have any other complaints, Suggestions, or questions related to the personal information of minors, you may send your questions to webmaster@opsnft.net We will review the issue as soon as possible and reply within 15 days after verifying your user identity.</span></p>
    </div>
</template>

<style scoped lang="scss" src="./PrivateProtocol.scss"></style>